<?php

require_once __DIR__ . "/../vendor/autoload.php";

use ILIAS\DI\Container;
use srag\CustomInputGUIs\SrGeogebra\Loader\CustomInputGUIsLoaderDetector;
use srag\Plugins\SrGeogebra\Upload\UploadService;
use srag\Plugins\SrGeogebra\Utils\SrGeogebraTrait;
use srag\RemovePluginDataConfirm\SrGeogebra\PluginUninstallTrait;

/**
 * Class ilSrGeogebraPlugin
 *
 * Generated by SrPluginGenerator v1.3.4
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilSrGeogebraPlugin extends ilPageComponentPlugin
{

    use PluginUninstallTrait;
    use SrGeogebraTrait;
    const PLUGIN_ID = "srgg";
    const PLUGIN_NAME = "SrGeogebra";
    const PLUGIN_CLASS_NAME = self::class;
    // Can't be in language file as languages aren't updated on a failed update
    const UPDATE_ERROR_MSG = "Update failed. Please add the file extension \"ggb\" into the ILIAS file upload whitelist. Please consult the documentation for more info.";
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * ilSrGeogebraPlugin constructor
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * @inheritDoc
     */
    public function getPluginName() : string
    {
        return self::PLUGIN_NAME;
    }


    /**
     * @inheritDoc
     */
    public function isValidParentType(/*string*/ $a_type) : bool
    {
        // Allow in all parent types
        return true;
    }


    /**
     * @inheritDoc
     */
    public function onDelete(/*array*/ $properties, /*string*/ $plugin_version)/*: void*/
    {
        if (self::dic()->ctrl()->getCmd() !== "moveAfter") {

        }
    }


    /**
     * @inheritDoc
     */
    public function onClone(/*array*/ &$properties, /*string*/ $plugin_version)/*: void*/
    {

    }


    /**
     * @inheritDoc
     */
    public function updateLanguages(/*?array*/ $a_lang_keys = null)/*:void*/
    {
        parent::updateLanguages($a_lang_keys);

        $this->installRemovePluginDataConfirmLanguages();
    }


    /**
     * @inheritDoc
     */
    protected function deleteData()/*: void*/
    {
        self::srGeogebra()->dropTables();
    }


    protected function beforeActivation()
    {
        return $this->checkSuffixAvailable(self::plugin()->translate("config_activation_error"));
    }


    protected function beforeUpdate()
    {
        return $this->checkSuffixAvailable(self::UPDATE_ERROR_MSG);
    }


    protected function checkSuffixAvailable($error_msg) {
        global $DIC;

        $whitelist = ilFileUtils::getValidExtensions();

        // Error if file extension "ggb" is not whitelisted upon plugin activation
        if (!in_array(UploadService::FILE_SUFFIX, $whitelist)) {
            ilUtil::sendFailure($error_msg, true);
            return false;
        }

        return true;
    }


    /**
     * @return bool
     */
    protected function shouldUseOneUpdateStepOnly() : bool
    {
        return false;
    }


    public function exchangeUIRendererAfterInitialization(Container $dic) : Closure
    {
        return CustomInputGUIsLoaderDetector::exchangeUIRendererAfterInitialization();
    }
}
