<?php

namespace srag\Plugins\SrGeogebra\Config;

use ilCheckboxInputGUI;
use ilNumberInputGUI;
use ilSelectInputGUI;
use ilSrGeogebraConfigGUI;
use srag\CustomInputGUIs\SrGeogebra\MultiSelectSearchNewInputGUI\MultiSelectSearchNewInputGUI;
use srag\Plugins\SrGeogebra\Forms\BaseAdvancedGeogebraFormGUI;
use srag\Plugins\SrGeogebra\Forms\GeogebraFormGUI;

/**
 * Class ConfigFormGUI
 *
 * Generated by SrPluginGenerator v1.3.4
 *
 * @package srag\Plugins\SrGeogebra\Config
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ConfigAdvancedGeogebraFormGUI extends BaseAdvancedGeogebraFormGUI
{
    const KEY_IMMUTABLE = "immutable";
    const KEY_DEFAULT_WIDTH = "default_width";
    const KEY_DEFAULT_HEIGHT = "default_height";
    const KEY_DEFAULT_DRAG_ZOOM = "default_enableShiftDragZoom";
    const KEY_DEFAULT_RESET = "default_showResetIcon";
    const KEY_DEFAULT_ALIGNMENT = "default_alignment";
    const IMMUTABLE_BLACKLIST = [
        self::KEY_IMMUTABLE
    ];

    protected function initFields()
    {
        parent::initFields();

        // Add at the beginning of fields array
        $this->fields = [self::KEY_DEFAULT_ALIGNMENT => [
                self::PROPERTY_CLASS => ilSelectInputGUI::class,
                self::PROPERTY_OPTIONS => [
                    GeogebraFormGUI::ALIGNMENT_LEFT => GeogebraFormGUI::ALIGNMENT_LEFT,
                    GeogebraFormGUI::ALIGNMENT_CENTER => GeogebraFormGUI::ALIGNMENT_CENTER,
                    GeogebraFormGUI::ALIGNMENT_RIGHT => GeogebraFormGUI::ALIGNMENT_RIGHT
                ]
            ]
        ] + $this->fields;

        $this->fields = [self::KEY_DEFAULT_RESET => [
                self::PROPERTY_CLASS    => ilCheckboxInputGUI::class
            ]
        ] + $this->fields;

        $this->fields = [self::KEY_DEFAULT_DRAG_ZOOM => [
                self::PROPERTY_CLASS    => ilCheckboxInputGUI::class
            ]
        ] + $this->fields;

        $this->fields = [self::KEY_DEFAULT_HEIGHT => [
                self::PROPERTY_CLASS    => ilNumberInputGUI::class
            ]
        ] + $this->fields;

        $this->fields = [self::KEY_DEFAULT_WIDTH => [
                self::PROPERTY_CLASS    => ilNumberInputGUI::class
            ]
        ] + $this->fields;

        $this->fields = [self::KEY_IMMUTABLE => [
                self::PROPERTY_CLASS    => MultiSelectSearchNewInputGUI::class,
                "setOptions" => [$this->prepareImmutableOptions()],
                "setInfo" => $this->txt("immutable_info")
            ]
        ] + $this->fields;
    }


    protected function prepareImmutableOptions() {
        $options = [];

        foreach (Repository::getInstance()->getFieldNames() as $field_name) {
            if (!in_array($field_name, self::IMMUTABLE_BLACKLIST)) {
                $options[$field_name] = $this->txt($field_name);
            };
        }

        return $options;
    }


    /**
     * @inheritDoc
     */
    protected function getValue(string $key)
    {
        $parent_result = parent::getValue($key);

        if (!is_null($parent_result)) {
            return $parent_result;
        }

        return self::srGeogebra()->config()->getValue($key);
    }


    /**
     * @inheritDoc
     */
    protected function storeValue(string $key, $value)/*: void*/
    {
        switch ($key) {
            default:
                self::srGeogebra()->config()->setValue($key, $value);
                break;
        }
    }


    /**
     * @inheritDoc
     */
    protected function initTitle()/*: void*/
    {
        $this->setTitle($this->txt("configuration"));
    }


    /**
     * @inheritDoc
     */
    protected function initCommands()/*: void*/
    {
        $this->addCommandButton(ilSrGeogebraConfigGUI::CMD_UPDATE_CONFIGURE, $this->txt("save"));
    }
}
