<?php

namespace srag\Plugins\SrGeogebra\Config;

use srag\Plugins\SrGeogebra\Utils\SrGeogebraTrait;
use ilSrGeogebraConfigGUI;
use ilSrGeogebraPlugin;
use srag\ActiveRecordConfig\SrGeogebra\Config\AbstractFactory;

/**
 * Class Factory
 *
 * Generated by SrPluginGenerator v1.3.4
 *
 * @package srag\Plugins\SrGeogebra\Config
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Factory extends AbstractFactory
{

    use SrGeogebraTrait;
    const PLUGIN_CLASS_NAME = ilSrGeogebraPlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * Factory constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @param ilSrGeogebraConfigGUI $parent
     *
     * @return ConfigFormGUI
     */
    public function newFormInstance(ilSrGeogebraConfigGUI $parent) : ConfigFormGUI
    {
        $form = new ConfigFormGUI($parent);

        return $form;
    }
}
