<?php

namespace srag\Plugins\SrGeogebra\Config;

use srag\Plugins\SrGeogebra\Utils\SrGeogebraTrait;
use ilSrGeogebraPlugin;
use srag\ActiveRecordConfig\SrGeogebra\Config\AbstractFactory;
use srag\ActiveRecordConfig\SrGeogebra\Config\AbstractRepository;
use srag\ActiveRecordConfig\SrGeogebra\Config\Config;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v1.3.4
 *
 * @package srag\Plugins\SrGeogebra\Config
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Repository extends AbstractRepository
{

    use SrGeogebraTrait;
    const PLUGIN_CLASS_NAME = ilSrGeogebraPlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * Repository constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @inheritDoc
     *
     * @return Factory
     */
    public function factory() : AbstractFactory
    {
        return Factory::getInstance();
    }


    /**
     * @inheritDoc
     */
    protected function getTableName() : string
    {
        return ilSrGeogebraPlugin::PLUGIN_ID . "_config";
    }


    /**
     * @inheritDoc
     */
    protected function getFields() : array
    {
        return [
            ConfigFormGUI::KEY_SOME => Config::TYPE_STRING
        ];
    }
}
