<?php

namespace srag\Plugins\SrGeogebra\Utils;

use srag\Plugins\SrGeogebra\Repository;

/**
 * Trait SrGeogebraTrait
 *
 * Generated by SrPluginGenerator v1.3.4
 *
 * @package srag\Plugins\SrGeogebra\Utils
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
trait SrGeogebraTrait
{

    /**
     * @return Repository
     */
    protected static function srGeogebra() : Repository
    {
        return Repository::getInstance();
    }
}
